### PR TITLE
add png versions for svg images

### PR DESCRIPTION
**Pull request by michzza**

### CODE REVIEW

**Review by AlbertBackenhof — CHANGES_REQUESTED** [review]
Images are too small. They need to be at least 1080 pixels wide. Most devices today have 1080p+ screens.

**Comment by ArianeParissis** [comment]
Ah agree with Albert, there's a risk the png look blurry with this resolution. 
Another comment: some images are from the old app layout (everything that had the old school wave, basically). In case you only want to add the latest images, these are the ones to delete: 

Screenshot 2024-02-14 at 11 36 40

Screenshot 2024-02-14 at 11 37 14

**Comment by michzza** [comment]
ok, thanks. 
I removed the unused ones and for the others, replaced the card images with ones that are 1080px wide, and icons with ones that are around 200px wide.

**Review by AlbertBackenhof — APPROVED** [review]
LGTM

**Comment by michzza** [comment]
> Ah agree with Albert, there's a risk the png look blurry with this resolution. Another comment: some images are from the old app layout (everything that had the old school wave, basically). In case you only want to add the latest images, these are the ones to delete:
> 
> Screenshot 2024-02-14 at 11 36 40 Screenshot 2024-02-14 at 11 37 14

The backend sends `beiwe/app/payment-failed-background.svg` as a background image for the privacy policy overview item. I also saw other overview items containing those wavy images. Are they not used anymore by the app?

**Comment by ArianeParissis** [comment]
> The backend sends `beiwe/app/payment-failed-background.svg` as a background image for the privacy policy overview item. I also saw other overview items containing those wavy images. Are they not used anymore by the app?

I think they are used by the old version of the app that was able to read .svg files. I'd say no need to duplicate these files as .png !
Screenshot 2024-02-14 at 14 15 53

**Pull request merged**
